// <auto-generated />
namespace obligatorio1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Presupuestos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Presupuestos));
        
        string IMigrationMetadata.Id
        {
            get { return "202011171201052_Presupuestos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
